apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-service

spec:
  replicas: 2

  selector:
    matchLabels:
      app: auth

  template:
    metadata:
      labels:
        app: auth

    spec:
      containers:
        name: auth-container
        image: auth-test-image
        port: 8080

  